/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq.udt.records;


import club.ttg.dnd5.jooq.udt.SpellDuration;

import org.jooq.impl.UDTRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpellDurationRecord extends UDTRecordImpl<SpellDurationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.spell_duration.value</code>.
     */
    public void setValue(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.spell_duration.value</code>.
     */
    public Long getValue() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.spell_duration.unit</code>.
     */
    public void setUnit(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.spell_duration.unit</code>.
     */
    public String getUnit() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.spell_duration.custom</code>.
     */
    public void setCustom(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.spell_duration.custom</code>.
     */
    public String getCustom() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.spell_duration.concentration</code>.
     */
    public void setConcentration(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.spell_duration.concentration</code>.
     */
    public Boolean getConcentration() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpellDurationRecord
     */
    public SpellDurationRecord() {
        super(SpellDuration.SPELL_DURATION);
    }

    /**
     * Create a detached, initialised SpellDurationRecord
     */
    public SpellDurationRecord(Long value, String unit, String custom, Boolean concentration) {
        super(SpellDuration.SPELL_DURATION);

        setValue(value);
        setUnit(unit);
        setCustom(custom);
        setConcentration(concentration);
        resetTouchedOnNotNull();
    }
}
