/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq.tables.records;


import club.ttg.dnd5.jooq.tables.JooqBookAuthors;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookAuthorsRecord extends TableRecordImpl<BookAuthorsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.book_authors.book_id</code>.
     */
    public void setBookId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.book_authors.book_id</code>.
     */
    public String getBookId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.book_authors.author_name</code>.
     */
    public void setAuthorName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.book_authors.author_name</code>.
     */
    public String getAuthorName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookAuthorsRecord
     */
    public BookAuthorsRecord() {
        super(JooqBookAuthors.BOOK_AUTHORS);
    }

    /**
     * Create a detached, initialised BookAuthorsRecord
     */
    public BookAuthorsRecord(String bookId, String authorName) {
        super(JooqBookAuthors.BOOK_AUTHORS);

        setBookId(bookId);
        setAuthorName(authorName);
        resetTouchedOnNotNull();
    }
}
