/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq.tables.records;


import club.ttg.dnd5.jooq.tables.JooqBooks;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BooksRecord extends UpdatableRecordImpl<BooksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.books.source_acronym</code>.
     */
    public void setSourceAcronym(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.books.source_acronym</code>.
     */
    public String getSourceAcronym() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.books.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.books.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.books.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.books.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.books.url</code>.
     */
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.books.url</code>.
     */
    public String getUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.books.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.books.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.books.english_name</code>.
     */
    public void setEnglishName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.books.english_name</code>.
     */
    public String getEnglishName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.books.alt_name</code>.
     */
    public void setAltName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.books.alt_name</code>.
     */
    public String getAltName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.books.description</code>.
     */
    public void setDescription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.books.description</code>.
     */
    public String getDescription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.books.type</code>.
     */
    public void setType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.books.type</code>.
     */
    public String getType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.books.book_date</code>.
     */
    public void setBookDate(LocalDate value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.books.book_date</code>.
     */
    public LocalDate getBookDate() {
        return (LocalDate) get(9);
    }

    /**
     * Setter for <code>public.books.image</code>.
     */
    public void setImage(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.books.image</code>.
     */
    public String getImage() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.books.translation_date</code>.
     */
    public void setTranslationDate(LocalDate value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.books.translation_date</code>.
     */
    public LocalDate getTranslationDate() {
        return (LocalDate) get(11);
    }

    /**
     * Setter for <code>public.books.username</code>.
     */
    public void setUsername(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.books.username</code>.
     */
    public String getUsername() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BooksRecord
     */
    public BooksRecord() {
        super(JooqBooks.BOOKS);
    }

    /**
     * Create a detached, initialised BooksRecord
     */
    public BooksRecord(String sourceAcronym, LocalDateTime createdAt, LocalDateTime updatedAt, String url, String name, String englishName, String altName, String description, String type, LocalDate bookDate, String image, LocalDate translationDate, String username) {
        super(JooqBooks.BOOKS);

        setSourceAcronym(sourceAcronym);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setUrl(url);
        setName(name);
        setEnglishName(englishName);
        setAltName(altName);
        setDescription(description);
        setType(type);
        setBookDate(bookDate);
        setImage(image);
        setTranslationDate(translationDate);
        setUsername(username);
        resetTouchedOnNotNull();
    }
}
