/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq.tables.records;


import club.ttg.dnd5.jooq.tables.JooqSpeciesGallery;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpeciesGalleryRecord extends TableRecordImpl<SpeciesGalleryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.species_gallery.species_id</code>.
     */
    public void setSpeciesId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.species_gallery.species_id</code>.
     */
    public String getSpeciesId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.species_gallery.gallery_url</code>.
     */
    public void setGalleryUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.species_gallery.gallery_url</code>.
     */
    public String getGalleryUrl() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpeciesGalleryRecord
     */
    public SpeciesGalleryRecord() {
        super(JooqSpeciesGallery.SPECIES_GALLERY);
    }

    /**
     * Create a detached, initialised SpeciesGalleryRecord
     */
    public SpeciesGalleryRecord(String speciesId, String galleryUrl) {
        super(JooqSpeciesGallery.SPECIES_GALLERY);

        setSpeciesId(speciesId);
        setGalleryUrl(galleryUrl);
        resetTouchedOnNotNull();
    }
}
