/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq.tables.records;


import club.ttg.dnd5.jooq.enums.SpeciesSize;
import club.ttg.dnd5.jooq.tables.JooqSpecies;

import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpeciesRecord extends UpdatableRecordImpl<SpeciesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.species.url</code>.
     */
    public void setUrl(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.species.url</code>.
     */
    public String getUrl() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.species.type</code>.
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.species.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.species.speed</code>.
     */
    public void setSpeed(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.species.speed</code>.
     */
    public Integer getSpeed() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.species.fly</code>.
     */
    public void setFly(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.species.fly</code>.
     */
    public Integer getFly() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.species.climb</code>.
     */
    public void setClimb(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.species.climb</code>.
     */
    public Integer getClimb() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.species.swim</code>.
     */
    public void setSwim(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.species.swim</code>.
     */
    public Integer getSwim() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.species.dark_vision</code>.
     */
    public void setDarkVision(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.species.dark_vision</code>.
     */
    public Integer getDarkVision() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.species.name</code>.
     */
    public void setName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.species.name</code>.
     */
    public String getName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.species.english</code>.
     */
    public void setEnglish(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.species.english</code>.
     */
    public String getEnglish() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.species.alternative</code>.
     */
    public void setAlternative(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.species.alternative</code>.
     */
    public String getAlternative() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.species.description</code>.
     */
    public void setDescription(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.species.description</code>.
     */
    public String getDescription() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.species.image_url</code>.
     */
    public void setImageUrl(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.species.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.species.is_hidden_entity</code>.
     */
    public void setIsHiddenEntity(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.species.is_hidden_entity</code>.
     */
    public Boolean getIsHiddenEntity() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>public.species.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.species.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.species.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.species.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>public.species.link_image_url</code>.
     */
    public void setLinkImageUrl(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.species.link_image_url</code>.
     */
    public String getLinkImageUrl() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.species.parent_url</code>.
     */
    public void setParentUrl(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.species.parent_url</code>.
     */
    public String getParentUrl() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.species.species_size</code>.
     */
    public void setSpeciesSize(SpeciesSize[] value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.species.species_size</code>.
     */
    public SpeciesSize[] getSpeciesSize() {
        return (SpeciesSize[]) get(17);
    }

    /**
     * Setter for <code>public.species.text</code>.
     */
    public void setText(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.species.text</code>.
     */
    public String getText() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.species.source</code>.
     */
    public void setSource(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.species.source</code>.
     */
    public String getSource() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.species.username</code>.
     */
    public void setUsername(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.species.username</code>.
     */
    public String getUsername() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.species.features</code>.
     */
    public void setFeatures(JSONB value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.species.features</code>.
     */
    public JSONB getFeatures() {
        return (JSONB) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpeciesRecord
     */
    public SpeciesRecord() {
        super(JooqSpecies.SPECIES);
    }

    /**
     * Create a detached, initialised SpeciesRecord
     */
    public SpeciesRecord(String url, String type, Integer speed, Integer fly, Integer climb, Integer swim, Integer darkVision, String name, String english, String alternative, String description, String imageUrl, Boolean isHiddenEntity, LocalDateTime createdAt, LocalDateTime updatedAt, String linkImageUrl, String parentUrl, SpeciesSize[] speciesSize, String text, String source, String username, JSONB features) {
        super(JooqSpecies.SPECIES);

        setUrl(url);
        setType(type);
        setSpeed(speed);
        setFly(fly);
        setClimb(climb);
        setSwim(swim);
        setDarkVision(darkVision);
        setName(name);
        setEnglish(english);
        setAlternative(alternative);
        setDescription(description);
        setImageUrl(imageUrl);
        setIsHiddenEntity(isHiddenEntity);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setLinkImageUrl(linkImageUrl);
        setParentUrl(parentUrl);
        setSpeciesSize(speciesSize);
        setText(text);
        setSource(source);
        setUsername(username);
        setFeatures(features);
        resetTouchedOnNotNull();
    }
}
