/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq.tables.records;


import club.ttg.dnd5.jooq.tables.JooqSpellSpeciesAffiliation;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpellSpeciesAffiliationRecord extends TableRecordImpl<SpellSpeciesAffiliationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.spell_species_affiliation.spell_url</code>.
     */
    public void setSpellUrl(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.spell_species_affiliation.spell_url</code>.
     */
    public String getSpellUrl() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>public.spell_species_affiliation.species_affiliation_url</code>.
     */
    public void setSpeciesAffiliationUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.spell_species_affiliation.species_affiliation_url</code>.
     */
    public String getSpeciesAffiliationUrl() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpellSpeciesAffiliationRecord
     */
    public SpellSpeciesAffiliationRecord() {
        super(JooqSpellSpeciesAffiliation.SPELL_SPECIES_AFFILIATION);
    }

    /**
     * Create a detached, initialised SpellSpeciesAffiliationRecord
     */
    public SpellSpeciesAffiliationRecord(String spellUrl, String speciesAffiliationUrl) {
        super(JooqSpellSpeciesAffiliation.SPELL_SPECIES_AFFILIATION);

        setSpellUrl(spellUrl);
        setSpeciesAffiliationUrl(speciesAffiliationUrl);
        resetTouchedOnNotNull();
    }
}
