/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq.tables.records;


import club.ttg.dnd5.jooq.tables.JooqSpell;

import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpellRecord extends UpdatableRecordImpl<SpellRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.spell.url</code>.
     */
    public void setUrl(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.spell.url</code>.
     */
    public String getUrl() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.spell.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.spell.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.spell.english</code>.
     */
    public void setEnglish(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.spell.english</code>.
     */
    public String getEnglish() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.spell.alternative</code>.
     */
    public void setAlternative(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.spell.alternative</code>.
     */
    public String getAlternative() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.spell.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.spell.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.spell.image_url</code>.
     */
    public void setImageUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.spell.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.spell.is_hidden_entity</code>.
     */
    public void setIsHiddenEntity(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.spell.is_hidden_entity</code>.
     */
    public Boolean getIsHiddenEntity() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.spell.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.spell.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.spell.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.spell.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.spell.username</code>.
     */
    public void setUsername(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.spell.username</code>.
     */
    public String getUsername() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.spell.level</code>.
     */
    public void setLevel(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.spell.level</code>.
     */
    public Long getLevel() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.spell.casting_time</code>.
     */
    public void setCastingTime(JSONB value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.spell.casting_time</code>.
     */
    public JSONB getCastingTime() {
        return (JSONB) get(11);
    }

    /**
     * Setter for <code>public.spell.upper</code>.
     */
    public void setUpper(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.spell.upper</code>.
     */
    public String getUpper() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.spell.source</code>.
     */
    public void setSource(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.spell.source</code>.
     */
    public String getSource() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.spell.source_page</code>.
     */
    public void setSourcePage(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.spell.source_page</code>.
     */
    public Long getSourcePage() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>public.spell.school</code>.
     */
    public void setSchool(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.spell.school</code>.
     */
    public String getSchool() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.spell.additional_type</code>.
     */
    public void setAdditionalType(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.spell.additional_type</code>.
     */
    public String getAdditionalType() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.spell.v</code>.
     */
    public void setV(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.spell.v</code>.
     */
    public Boolean getV() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>public.spell.s</code>.
     */
    public void setS(Boolean value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.spell.s</code>.
     */
    public Boolean getS() {
        return (Boolean) get(18);
    }

    /**
     * Setter for <code>public.spell.m</code>.
     */
    public void setM(JSONB value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.spell.m</code>.
     */
    public JSONB getM() {
        return (JSONB) get(19);
    }

    /**
     * Setter for <code>public.spell.range</code>.
     */
    public void setRange(JSONB value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.spell.range</code>.
     */
    public JSONB getRange() {
        return (JSONB) get(20);
    }

    /**
     * Setter for <code>public.spell.duration</code>.
     */
    public void setDuration(JSONB value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.spell.duration</code>.
     */
    public JSONB getDuration() {
        return (JSONB) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpellRecord
     */
    public SpellRecord() {
        super(JooqSpell.SPELL);
    }

    /**
     * Create a detached, initialised SpellRecord
     */
    public SpellRecord(String url, String name, String english, String alternative, String description, String imageUrl, Boolean isHiddenEntity, LocalDateTime createdAt, LocalDateTime updatedAt, String username, Long level, JSONB castingTime, String upper, String source, Long sourcePage, String school, String additionalType, Boolean v, Boolean s, JSONB m, JSONB range, JSONB duration) {
        super(JooqSpell.SPELL);

        setUrl(url);
        setName(name);
        setEnglish(english);
        setAlternative(alternative);
        setDescription(description);
        setImageUrl(imageUrl);
        setIsHiddenEntity(isHiddenEntity);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setUsername(username);
        setLevel(level);
        setCastingTime(castingTime);
        setUpper(upper);
        setSource(source);
        setSourcePage(sourcePage);
        setSchool(school);
        setAdditionalType(additionalType);
        setV(v);
        setS(s);
        setM(m);
        setRange(range);
        setDuration(duration);
        resetTouchedOnNotNull();
    }
}
