/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq.tables.records;


import club.ttg.dnd5.jooq.tables.JooqUserRole;

import java.util.UUID;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRoleRecord extends TableRecordImpl<UserRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_role.role_id</code>.
     */
    public void setRoleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_role.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_role.user_uuid</code>.
     */
    public void setUserUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_role.user_uuid</code>.
     */
    public UUID getUserUuid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRoleRecord
     */
    public UserRoleRecord() {
        super(JooqUserRole.USER_ROLE);
    }

    /**
     * Create a detached, initialised UserRoleRecord
     */
    public UserRoleRecord(Long roleId, UUID userUuid) {
        super(JooqUserRole.USER_ROLE);

        setRoleId(roleId);
        setUserUuid(userUuid);
        resetTouchedOnNotNull();
    }
}
