/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq;


import club.ttg.dnd5.jooq.tables.JooqGlossary;
import club.ttg.dnd5.jooq.tables.JooqSpecies;
import club.ttg.dnd5.jooq.tables.JooqSpell;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index GLOSSARY_NAME_INDEX = Internal.createIndex(DSL.name("glossary_name_index"), JooqGlossary.GLOSSARY, new OrderField[] { JooqGlossary.GLOSSARY.NAME, JooqGlossary.GLOSSARY.ENGLISH, JooqGlossary.GLOSSARY.ALTERNATIVE }, false);
    public static final Index NAME_INDEX = Internal.createIndex(DSL.name("name_index"), JooqSpecies.SPECIES, new OrderField[] { JooqSpecies.SPECIES.NAME, JooqSpecies.SPECIES.ENGLISH, JooqSpecies.SPECIES.ALTERNATIVE }, false);
    public static final Index SPELL_NAME_INDEX = Internal.createIndex(DSL.name("spell_name_index"), JooqSpell.SPELL, new OrderField[] { JooqSpell.SPELL.NAME, JooqSpell.SPELL.ENGLISH, JooqSpell.SPELL.ALTERNATIVE }, false);
}
