/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq;


import club.ttg.dnd5.jooq.tables.JooqBookAuthors;
import club.ttg.dnd5.jooq.tables.JooqBooks;
import club.ttg.dnd5.jooq.tables.JooqDatabasechangelog;
import club.ttg.dnd5.jooq.tables.JooqDatabasechangeloglock;
import club.ttg.dnd5.jooq.tables.JooqGlossary;
import club.ttg.dnd5.jooq.tables.JooqOneTimeTokens;
import club.ttg.dnd5.jooq.tables.JooqRoles;
import club.ttg.dnd5.jooq.tables.JooqSpecies;
import club.ttg.dnd5.jooq.tables.JooqSpeciesGallery;
import club.ttg.dnd5.jooq.tables.JooqSpell;
import club.ttg.dnd5.jooq.tables.JooqSpellSpeciesAffiliation;
import club.ttg.dnd5.jooq.tables.JooqTranslationAuthors;
import club.ttg.dnd5.jooq.tables.JooqUserRole;
import club.ttg.dnd5.jooq.tables.JooqUsers;
import club.ttg.dnd5.jooq.udt.SpellDuration;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.UDT;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.book_authors</code>.
     */
    public final JooqBookAuthors BOOK_AUTHORS = JooqBookAuthors.BOOK_AUTHORS;

    /**
     * The table <code>public.books</code>.
     */
    public final JooqBooks BOOKS = JooqBooks.BOOKS;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final JooqDatabasechangelog DATABASECHANGELOG = JooqDatabasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final JooqDatabasechangeloglock DATABASECHANGELOGLOCK = JooqDatabasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.glossary</code>.
     */
    public final JooqGlossary GLOSSARY = JooqGlossary.GLOSSARY;

    /**
     * The table <code>public.one_time_tokens</code>.
     */
    public final JooqOneTimeTokens ONE_TIME_TOKENS = JooqOneTimeTokens.ONE_TIME_TOKENS;

    /**
     * The table <code>public.roles</code>.
     */
    public final JooqRoles ROLES = JooqRoles.ROLES;

    /**
     * The table <code>public.species</code>.
     */
    public final JooqSpecies SPECIES = JooqSpecies.SPECIES;

    /**
     * The table <code>public.species_gallery</code>.
     */
    public final JooqSpeciesGallery SPECIES_GALLERY = JooqSpeciesGallery.SPECIES_GALLERY;

    /**
     * The table <code>public.spell</code>.
     */
    public final JooqSpell SPELL = JooqSpell.SPELL;

    /**
     * The table <code>public.spell_species_affiliation</code>.
     */
    public final JooqSpellSpeciesAffiliation SPELL_SPECIES_AFFILIATION = JooqSpellSpeciesAffiliation.SPELL_SPECIES_AFFILIATION;

    /**
     * The table <code>public.translation_authors</code>.
     */
    public final JooqTranslationAuthors TRANSLATION_AUTHORS = JooqTranslationAuthors.TRANSLATION_AUTHORS;

    /**
     * The table <code>public.user_role</code>.
     */
    public final JooqUserRole USER_ROLE = JooqUserRole.USER_ROLE;

    /**
     * The table <code>public.users</code>.
     */
    public final JooqUsers USERS = JooqUsers.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            JooqBookAuthors.BOOK_AUTHORS,
            JooqBooks.BOOKS,
            JooqDatabasechangelog.DATABASECHANGELOG,
            JooqDatabasechangeloglock.DATABASECHANGELOGLOCK,
            JooqGlossary.GLOSSARY,
            JooqOneTimeTokens.ONE_TIME_TOKENS,
            JooqRoles.ROLES,
            JooqSpecies.SPECIES,
            JooqSpeciesGallery.SPECIES_GALLERY,
            JooqSpell.SPELL,
            JooqSpellSpeciesAffiliation.SPELL_SPECIES_AFFILIATION,
            JooqTranslationAuthors.TRANSLATION_AUTHORS,
            JooqUserRole.USER_ROLE,
            JooqUsers.USERS
        );
    }

    @Override
    public final List<UDT<?>> getUDTs() {
        return Arrays.asList(
            SpellDuration.SPELL_DURATION
        );
    }
}
