/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq;


import club.ttg.dnd5.jooq.tables.JooqBookAuthors;
import club.ttg.dnd5.jooq.tables.JooqBooks;
import club.ttg.dnd5.jooq.tables.JooqDatabasechangelog;
import club.ttg.dnd5.jooq.tables.JooqDatabasechangeloglock;
import club.ttg.dnd5.jooq.tables.JooqGlossary;
import club.ttg.dnd5.jooq.tables.JooqOneTimeTokens;
import club.ttg.dnd5.jooq.tables.JooqRoles;
import club.ttg.dnd5.jooq.tables.JooqSpecies;
import club.ttg.dnd5.jooq.tables.JooqSpeciesGallery;
import club.ttg.dnd5.jooq.tables.JooqSpell;
import club.ttg.dnd5.jooq.tables.JooqSpellSpeciesAffiliation;
import club.ttg.dnd5.jooq.tables.JooqTranslationAuthors;
import club.ttg.dnd5.jooq.tables.JooqUserRole;
import club.ttg.dnd5.jooq.tables.JooqUsers;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.book_authors</code>.
     */
    public static final JooqBookAuthors BOOK_AUTHORS = JooqBookAuthors.BOOK_AUTHORS;

    /**
     * The table <code>public.books</code>.
     */
    public static final JooqBooks BOOKS = JooqBooks.BOOKS;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final JooqDatabasechangelog DATABASECHANGELOG = JooqDatabasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final JooqDatabasechangeloglock DATABASECHANGELOGLOCK = JooqDatabasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.glossary</code>.
     */
    public static final JooqGlossary GLOSSARY = JooqGlossary.GLOSSARY;

    /**
     * The table <code>public.one_time_tokens</code>.
     */
    public static final JooqOneTimeTokens ONE_TIME_TOKENS = JooqOneTimeTokens.ONE_TIME_TOKENS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final JooqRoles ROLES = JooqRoles.ROLES;

    /**
     * The table <code>public.species</code>.
     */
    public static final JooqSpecies SPECIES = JooqSpecies.SPECIES;

    /**
     * The table <code>public.species_gallery</code>.
     */
    public static final JooqSpeciesGallery SPECIES_GALLERY = JooqSpeciesGallery.SPECIES_GALLERY;

    /**
     * The table <code>public.spell</code>.
     */
    public static final JooqSpell SPELL = JooqSpell.SPELL;

    /**
     * The table <code>public.spell_species_affiliation</code>.
     */
    public static final JooqSpellSpeciesAffiliation SPELL_SPECIES_AFFILIATION = JooqSpellSpeciesAffiliation.SPELL_SPECIES_AFFILIATION;

    /**
     * The table <code>public.translation_authors</code>.
     */
    public static final JooqTranslationAuthors TRANSLATION_AUTHORS = JooqTranslationAuthors.TRANSLATION_AUTHORS;

    /**
     * The table <code>public.user_role</code>.
     */
    public static final JooqUserRole USER_ROLE = JooqUserRole.USER_ROLE;

    /**
     * The table <code>public.users</code>.
     */
    public static final JooqUsers USERS = JooqUsers.USERS;
}
