/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq;


import club.ttg.dnd5.jooq.udt.SpellDuration;


/**
 * Convenience access to all UDTs in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UDTs {

    /**
     * The type <code>public.spell_duration</code>
     */
    public static final SpellDuration SPELL_DURATION = SpellDuration.SPELL_DURATION;
}
