/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq.udt.paths;


import club.ttg.dnd5.jooq.udt.SpellDuration;
import club.ttg.dnd5.jooq.udt.records.SpellDurationRecord;

import org.jooq.Binding;
import org.jooq.Comment;
import org.jooq.DataType;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.RecordQualifier;
import org.jooq.UDTField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.UDTPathTableFieldImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpellDurationPath<R extends Record, T> extends UDTPathTableFieldImpl<R, SpellDurationRecord, T> {

    private static final long serialVersionUID = 1L;

    /**
     * The attribute <code>public.spell_duration.value</code>.
     */
    public final UDTField<SpellDurationRecord, Long> VALUE = Internal.createUDTPathField(DSL.name("value"), SQLDataType.BIGINT, this, "", UDTField.class);

    /**
     * The attribute <code>public.spell_duration.unit</code>.
     */
    public final UDTField<SpellDurationRecord, String> UNIT = Internal.createUDTPathField(DSL.name("unit"), SQLDataType.VARCHAR(25), this, "", UDTField.class);

    /**
     * The attribute <code>public.spell_duration.custom</code>.
     */
    public final UDTField<SpellDurationRecord, String> CUSTOM = Internal.createUDTPathField(DSL.name("custom"), SQLDataType.VARCHAR(25), this, "", UDTField.class);

    /**
     * The attribute <code>public.spell_duration.concentration</code>.
     */
    public final UDTField<SpellDurationRecord, Boolean> CONCENTRATION = Internal.createUDTPathField(DSL.name("concentration"), SQLDataType.BOOLEAN, this, "", UDTField.class);

    public SpellDurationPath(Name name, DataType<T> type, RecordQualifier<R> qualifier, Comment comment, Binding<?, T> binding) {
        super(name, type, qualifier, SpellDuration.SPELL_DURATION, comment, binding);
    }
}
