/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq.tables;


import club.ttg.dnd5.jooq.Keys;
import club.ttg.dnd5.jooq.Public;
import club.ttg.dnd5.jooq.tables.JooqSpecies.SpeciesPath;
import club.ttg.dnd5.jooq.tables.JooqSpell.SpellPath;
import club.ttg.dnd5.jooq.tables.records.SpellSpeciesAffiliationRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JooqSpellSpeciesAffiliation extends TableImpl<SpellSpeciesAffiliationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.spell_species_affiliation</code>
     */
    public static final JooqSpellSpeciesAffiliation SPELL_SPECIES_AFFILIATION = new JooqSpellSpeciesAffiliation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpellSpeciesAffiliationRecord> getRecordType() {
        return SpellSpeciesAffiliationRecord.class;
    }

    /**
     * The column <code>public.spell_species_affiliation.spell_url</code>.
     */
    public final TableField<SpellSpeciesAffiliationRecord, String> SPELL_URL = createField(DSL.name("spell_url"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column
     * <code>public.spell_species_affiliation.species_affiliation_url</code>.
     */
    public final TableField<SpellSpeciesAffiliationRecord, String> SPECIES_AFFILIATION_URL = createField(DSL.name("species_affiliation_url"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private JooqSpellSpeciesAffiliation(Name alias, Table<SpellSpeciesAffiliationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JooqSpellSpeciesAffiliation(Name alias, Table<SpellSpeciesAffiliationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.spell_species_affiliation</code> table
     * reference
     */
    public JooqSpellSpeciesAffiliation(String alias) {
        this(DSL.name(alias), SPELL_SPECIES_AFFILIATION);
    }

    /**
     * Create an aliased <code>public.spell_species_affiliation</code> table
     * reference
     */
    public JooqSpellSpeciesAffiliation(Name alias) {
        this(alias, SPELL_SPECIES_AFFILIATION);
    }

    /**
     * Create a <code>public.spell_species_affiliation</code> table reference
     */
    public JooqSpellSpeciesAffiliation() {
        this(DSL.name("spell_species_affiliation"), null);
    }

    public <O extends Record> JooqSpellSpeciesAffiliation(Table<O> path, ForeignKey<O, SpellSpeciesAffiliationRecord> childPath, InverseForeignKey<O, SpellSpeciesAffiliationRecord> parentPath) {
        super(path, childPath, parentPath, SPELL_SPECIES_AFFILIATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SpellSpeciesAffiliationPath extends JooqSpellSpeciesAffiliation implements Path<SpellSpeciesAffiliationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SpellSpeciesAffiliationPath(Table<O> path, ForeignKey<O, SpellSpeciesAffiliationRecord> childPath, InverseForeignKey<O, SpellSpeciesAffiliationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SpellSpeciesAffiliationPath(Name alias, Table<SpellSpeciesAffiliationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SpellSpeciesAffiliationPath as(String alias) {
            return new SpellSpeciesAffiliationPath(DSL.name(alias), this);
        }

        @Override
        public SpellSpeciesAffiliationPath as(Name alias) {
            return new SpellSpeciesAffiliationPath(alias, this);
        }

        @Override
        public SpellSpeciesAffiliationPath as(Table<?> alias) {
            return new SpellSpeciesAffiliationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<SpellSpeciesAffiliationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SPELL_SPECIES_AFFILIATION__FK_SPESPEAFF_ON_SPECIES, Keys.SPELL_SPECIES_AFFILIATION__FK_SPESPEAFF_ON_SPELL);
    }

    private transient SpeciesPath _species;

    /**
     * Get the implicit join path to the <code>public.species</code> table.
     */
    public SpeciesPath species() {
        if (_species == null)
            _species = new SpeciesPath(this, Keys.SPELL_SPECIES_AFFILIATION__FK_SPESPEAFF_ON_SPECIES, null);

        return _species;
    }

    private transient SpellPath _spell;

    /**
     * Get the implicit join path to the <code>public.spell</code> table.
     */
    public SpellPath spell() {
        if (_spell == null)
            _spell = new SpellPath(this, Keys.SPELL_SPECIES_AFFILIATION__FK_SPESPEAFF_ON_SPELL, null);

        return _spell;
    }

    @Override
    public JooqSpellSpeciesAffiliation as(String alias) {
        return new JooqSpellSpeciesAffiliation(DSL.name(alias), this);
    }

    @Override
    public JooqSpellSpeciesAffiliation as(Name alias) {
        return new JooqSpellSpeciesAffiliation(alias, this);
    }

    @Override
    public JooqSpellSpeciesAffiliation as(Table<?> alias) {
        return new JooqSpellSpeciesAffiliation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqSpellSpeciesAffiliation rename(String name) {
        return new JooqSpellSpeciesAffiliation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqSpellSpeciesAffiliation rename(Name name) {
        return new JooqSpellSpeciesAffiliation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqSpellSpeciesAffiliation rename(Table<?> name) {
        return new JooqSpellSpeciesAffiliation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JooqSpellSpeciesAffiliation where(Condition condition) {
        return new JooqSpellSpeciesAffiliation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JooqSpellSpeciesAffiliation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JooqSpellSpeciesAffiliation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JooqSpellSpeciesAffiliation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JooqSpellSpeciesAffiliation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JooqSpellSpeciesAffiliation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JooqSpellSpeciesAffiliation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JooqSpellSpeciesAffiliation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JooqSpellSpeciesAffiliation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JooqSpellSpeciesAffiliation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
