/*
 * This file is generated by jOOQ.
 */
package club.ttg.dnd5.jooq.tables;


import club.ttg.dnd5.jooq.Keys;
import club.ttg.dnd5.jooq.Public;
import club.ttg.dnd5.jooq.tables.JooqBooks.BooksPath;
import club.ttg.dnd5.jooq.tables.records.TranslationAuthorsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JooqTranslationAuthors extends TableImpl<TranslationAuthorsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.translation_authors</code>
     */
    public static final JooqTranslationAuthors TRANSLATION_AUTHORS = new JooqTranslationAuthors();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TranslationAuthorsRecord> getRecordType() {
        return TranslationAuthorsRecord.class;
    }

    /**
     * The column <code>public.translation_authors.translation_id</code>.
     */
    public final TableField<TranslationAuthorsRecord, String> TRANSLATION_ID = createField(DSL.name("translation_id"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.translation_authors.author_name</code>.
     */
    public final TableField<TranslationAuthorsRecord, String> AUTHOR_NAME = createField(DSL.name("author_name"), SQLDataType.VARCHAR(255), this, "");

    private JooqTranslationAuthors(Name alias, Table<TranslationAuthorsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JooqTranslationAuthors(Name alias, Table<TranslationAuthorsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.translation_authors</code> table reference
     */
    public JooqTranslationAuthors(String alias) {
        this(DSL.name(alias), TRANSLATION_AUTHORS);
    }

    /**
     * Create an aliased <code>public.translation_authors</code> table reference
     */
    public JooqTranslationAuthors(Name alias) {
        this(alias, TRANSLATION_AUTHORS);
    }

    /**
     * Create a <code>public.translation_authors</code> table reference
     */
    public JooqTranslationAuthors() {
        this(DSL.name("translation_authors"), null);
    }

    public <O extends Record> JooqTranslationAuthors(Table<O> path, ForeignKey<O, TranslationAuthorsRecord> childPath, InverseForeignKey<O, TranslationAuthorsRecord> parentPath) {
        super(path, childPath, parentPath, TRANSLATION_AUTHORS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TranslationAuthorsPath extends JooqTranslationAuthors implements Path<TranslationAuthorsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TranslationAuthorsPath(Table<O> path, ForeignKey<O, TranslationAuthorsRecord> childPath, InverseForeignKey<O, TranslationAuthorsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TranslationAuthorsPath(Name alias, Table<TranslationAuthorsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TranslationAuthorsPath as(String alias) {
            return new TranslationAuthorsPath(DSL.name(alias), this);
        }

        @Override
        public TranslationAuthorsPath as(Name alias) {
            return new TranslationAuthorsPath(alias, this);
        }

        @Override
        public TranslationAuthorsPath as(Table<?> alias) {
            return new TranslationAuthorsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<TranslationAuthorsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TRANSLATION_AUTHORS__FK_TRANSLATION_AUTHORS_ON_BOOK);
    }

    private transient BooksPath _books;

    /**
     * Get the implicit join path to the <code>public.books</code> table.
     */
    public BooksPath books() {
        if (_books == null)
            _books = new BooksPath(this, Keys.TRANSLATION_AUTHORS__FK_TRANSLATION_AUTHORS_ON_BOOK, null);

        return _books;
    }

    @Override
    public JooqTranslationAuthors as(String alias) {
        return new JooqTranslationAuthors(DSL.name(alias), this);
    }

    @Override
    public JooqTranslationAuthors as(Name alias) {
        return new JooqTranslationAuthors(alias, this);
    }

    @Override
    public JooqTranslationAuthors as(Table<?> alias) {
        return new JooqTranslationAuthors(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqTranslationAuthors rename(String name) {
        return new JooqTranslationAuthors(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqTranslationAuthors rename(Name name) {
        return new JooqTranslationAuthors(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JooqTranslationAuthors rename(Table<?> name) {
        return new JooqTranslationAuthors(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JooqTranslationAuthors where(Condition condition) {
        return new JooqTranslationAuthors(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JooqTranslationAuthors where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JooqTranslationAuthors where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JooqTranslationAuthors where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JooqTranslationAuthors where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JooqTranslationAuthors where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JooqTranslationAuthors where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JooqTranslationAuthors where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JooqTranslationAuthors whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JooqTranslationAuthors whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
