name: Deploy
run-name: Deploy ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build, Push and Deploy
        uses: TTG-Club/shared-workflows/standard@v1
        with:
          application_id: ${{ github.ref_name == 'main' && secrets.DOKPLOY_APP_ID_PROD || secrets.DOKPLOY_APP_ID_DEV }}
          registry_url: ${{ secrets.REGISTRY_URL }}
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
          dokploy_url: ${{ secrets.DOKPLOY_URL }}
          dokploy_api_key: ${{ secrets.DOKPLOY_API_KEY }}
          cosign_private_key: ${{ secrets.COSIGN_PRIVATE_KEY }}
