name: Rollback
run-name: Rollback to ${{ inputs.target_sha }} on ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Rollback env'
        required: true
        default: 'development'
        type: choice
        options:
          - production
          - development
      target_sha:
        description: 'SHA of the commit or tag to be returned (for example, sha-dbf7c01)'
        required: true
        type: string

env:
  REGISTRY: ${{ secrets.REGISTRY_URL }}
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  tag-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Set lowercase image name
        run: echo "IMAGE_NAME=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ZOT_USERNAME }}
          password: ${{ secrets.ZOT_PASSWORD }}

      - name: Retag Image in registry
        run: |
          TARGET_TAG=${{ inputs.environment == 'production' && 'latest' || 'dev-latest' }}
          SOURCE_IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.target_sha }}"
          DEST_IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TARGET_TAG"
          
          echo "Moving tag $TARGET_TAG to point at ${{ inputs.target_sha }}..."
          
          docker run --rm quay.io/skopeo/stable:latest copy \
            --src-creds "${{ secrets.ZOT_USERNAME }}:${{ secrets.ZOT_PASSWORD }}" \
            --dest-creds "${{ secrets.ZOT_USERNAME }}:${{ secrets.ZOT_PASSWORD }}" \
            "docker://$SOURCE_IMAGE" "docker://$DEST_IMAGE"

      - name: Determine App ID
        run: |
          if [ "${{ inputs.environment }}" == "production" ]; then
            echo "APP_ID=${{ secrets.DOKPLOY_APP_ID_PROD }}" >> $GITHUB_ENV
          else
            echo "APP_ID=${{ secrets.DOKPLOY_APP_ID_DEV }}" >> $GITHUB_ENV
          fi

      - name: Dokploy Deployment
        uses: benbristow/dokploy-deploy-action@0.2.2
        with:
          api_token: ${{ secrets.DOKPLOY_API_KEY }}
          application_id: ${{ env.APP_ID }}
          dokploy_url: ${{ secrets.DOKPLOY_URL }}
          service_type: application